### ISSUE TITLE
Requires Udon

### ISSUE THREAD

**Issue by ShayBox** [BocuD/VRChatApiTools#3]
Fails to import/compile without Udon which does not exist in Avatar SDK
```
Assets\BocuD\VRChatApiTools\ApiFileHelperAsync.cs(10,11): error CS0234: The type or namespace name 'Udon' does not exist in the namespace 'VRC' (are you missing an assembly reference?)
...
```

**Comment by BocuD** [comment]
This issue should now be solved thanks to @Varneon's commit.

**Comment by ShayBox** [comment]
Oh wow that was fast, Thank you 👍
I hope to port my upload/thumbnail tool to use this so I can speed up updating with async

**Comment by BocuD** [comment]
Awesome, yeah that is what it is meant for (among other things!)
I would like to make BuildHelper compatible with the avatar SDK one day but that'll probably take a while. All the relevant methods should already be there though in ApiTools, at least for modifying images :)

**Comment by ShayBox** [comment]
Using the git dist I get this now
```
Library\PackageCache\com.bocud.vrcapitools@8ad453b39d\Editor\ApiFileHelperAsync.cs(9,23): error CS0234: The type or namespace name 'ApiFileHelper' does not exist in the namespace 'VRC.Core' (are you missing an assembly reference?)
...
Library\PackageCache\com.bocud.vrcapitools@8ad453b39d\Editor\VRChatApiToolsEditor.cs(14,23): error CS0246: The type or namespace name 'EditorCoroutine' could not be found (are you missing a using directive or an assembly reference?)
...
Library\PackageCache\com.bocud.vrcapitools@8ad453b39d\Editor\VRChatApiToolsEditor.cs(15,23): error CS0246: The type or namespace name 'EditorCoroutine' could not be found (are you missing a using directive or an assembly reference?)
...
```

**Comment by Varneon** [comment]
Both the **Editor** and **Runtime** folders in **Packages/com.bocud.vrcapitools** have **.asmdef** files in them, which define the assemblies for the scripts.

Could you take a look at them and see if any of the entries under **Assembly Definition References** are invalid?

![image](https://user-images.githubusercontent.com/26690821/185490331-80e6cf3e-f8bd-4812-a963-583ad5b5d391.png)
![image](https://user-images.githubusercontent.com/26690821/185490390-ee953814-6cdd-4c42-b4fb-43d62b8e9c0d.png)

Also, which VRCSDK version are you using?

-Varneon

**Comment by ShayBox** [comment]
I'm using the latest stable unity package from the website, the beta sdk still has some bugs from my testing, and I don't trust VRChat or their creator companion at this point.

I reimported the git dist but there's no folder/files in `Assets` or `Packages` it seems to be in `Library` from the error messages but I can't see how to access that within Unity

**Comment by Varneon** [comment]
I have just tested with the latest avatar SDK from the website and I'm able to reproduce this.

![image](https://user-images.githubusercontent.com/26690821/185557707-2a155c70-6b5d-4313-b86b-89c52bd5f33b.png)
![image](https://user-images.githubusercontent.com/26690821/185557743-0f18dac1-7fc6-4f64-9aff-ff258d2b13e8.png)

The issue is that VRChat hasn't set up the assembly definitions for their SDK's files for the "live" SDK. (The latest SDKs accessible via VRChat Creator Companion are located in Packages, which requires them to be contained in an assembly)

The only way to make VRChatApiTools backwards compatible with the non-Packages SDKs would be to create a release with all files located in the Assets folder without assembly definitions (Will talk about that with @BocuD)

In the meanwhile you could try importing the SDK with VRChat Creator Companion (https://vcc.docs.vrchat.com/) to get the latest SDK which VRChatApiTools is compatible with

**Comment by ShayBox** [comment]
I'll just wait for the beta sdk to be stable, hopefully they fix the remaining bugs before then.  
It's probably not worth the effort since future sdk updates will be through git dist not the unity packages, the current unity packages already have an importer for updating to the next version when they release it.
