### ISSUE TITLE
SDK 3.4.0 incompatibility

### ISSUE THREAD

**Issue by rhaamo** [BocuD/VRChatApiTools#8]
Upgraded a project to the cursed 3.4.0 SDK and got the following:
```
Library\PackageCache\com.bocud.vrcapitools@5d23ceab84\Editor\VRChatApiUploaderAsync.cs(83,62): error CS0117: 'AnalyticsSDK' does not contain a definition for 'AvatarUploaded'
Library\PackageCache\com.bocud.vrcapitools@5d23ceab84\Editor\VRChatApiUploaderAsync.cs(84,39): error CS0117: 'AnalyticsSDK' does not contain a definition for 'WorldUploaded'
```

Reproduced from an empty project with 3.4.0 and latest .unitypackage and from git.

Downgrading SDK to 3.3.0 obviously resolves the issue.

Looks like the method isn't available anymore in the new SDK.

**Comment by DrakenStark** [comment]
Looked into this, seems in lines 83 and 84 just need to reflect the new function names and change the blueprint argument to it's id as shown here:

From:
                    if (blueprint is ApiAvatar) AnalyticsSDK.AvatarUploaded(blueprint, true);
                    else AnalyticsSDK.WorldUploaded(blueprint, true);

To:
                    if (blueprint is ApiAvatar) AnalyticsSDK.AvatarUploadFailed(blueprint.id, true);
                    else AnalyticsSDK.WorldUploadFailed(blueprint.id, true);

**Comment by DrakenStark** [comment]
Created a pull request for this issue: https://github.com/BocuD/VRChatApiTools/pull/9

**Comment by BocuD** [comment]
After making some changes the issue was resolved, you should be able to install the latest version and no longer run into any issues. There will hopefully be a proper release soon to work with the new SDK APIs, depending on how much free time i have to work on it. I also updated the readmes for my repositorys to add the CreatorCompanion listings. I suggest everyone to switch to using it as updates will be a lot easier :) https://bocud.github.io/BocuDPackages/
